# Spring properties
spring:
  application:
     name: oauth-service

# Discovery Server Access
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5

# HTTP Server
server:
  port: 4444 # HTTP (Tomcat) port
